# Generated by Django 5.1.3 on 2025-02-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Calle')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('water_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa de agua')),
                ('sewer_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa de alcantarilla')),
                ('mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mora')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Year Period',
                'verbose_name_plural': 'Year Periods',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_data', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='RUC')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('has_meter', models.BooleanField(default=False)),
                ('installation_date', models.DateField(verbose_name='Reading Date')),
                ('water_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa de agua')),
                ('sewer_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa de alcantarilla')),
                ('meter_code', models.CharField(max_length=50, unique=True, verbose_name='Meter Code')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.calle')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.category')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='Reading Date')),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Reading (m³)')),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Previous Reading (m³)')),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumption (m³)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=10, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
                'unique_together': {('customer', 'reading_date')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=50, verbose_name='Payment Method')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='agua.reading')),
            ],
        ),
        migrations.AddField(
            model_name='calle',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.zona'),
        ),
    ]
