# Generated by Django 5.1.3 on 2025-03-18 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Calle')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Year Period',
                'verbose_name_plural': 'Year Periods',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('cortado', 'Cortado')], default='activo', max_length=10)),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='RUC')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono/Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('has_meter', models.BooleanField(default=False, verbose_name='¿Tiene medidor?')),
                ('installation_date', models.DateField(verbose_name='Fecha de instalación')),
                ('meter_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de medidor')),
                ('cutoff_date', models.DateField(blank=True, null=True, verbose_name='Fecha de corte')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.calle')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_of_issue', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('cut_off_date', models.DateField(blank=True, null=True)),
                ('reading_date', models.DateField()),
                ('current_reading', models.IntegerField()),
                ('previous_reading', models.IntegerField(blank=True, null=True)),
                ('consumption', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.invoice')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agua.reading')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_consumption', models.IntegerField(blank=True, null=True, verbose_name='Consumo Mínimo (m³)')),
                ('max_consumption', models.IntegerField(blank=True, null=True, verbose_name='Consumo Máximo (m³)')),
                ('price_water', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de agua')),
                ('price_sewer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de alcantarillado')),
                ('extra_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Tarifa Fija')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.category', verbose_name='Categoría')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_tariff', to='agua.tariff'),
        ),
        migrations.AddField(
            model_name='calle',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.zona'),
        ),
    ]
