# Generated by Django 5.1.3 on 2025-02-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
    ]
