# Generated by Django 5.1.3 on 2025-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reading',
            name='total_sewer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reading',
            name='total_water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
