# Generated by Django 5.1.3 on 2025-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='cut_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
