# Generated by Django 5.1.3 on 2025-03-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_reading_fixed_charge_reading_total_sewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agua.service')),
            ],
        ),
    ]
