# Generated by Django 5.1.3 on 2025-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_alter_reading_cut_off_date_alter_reading_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
