# Generated by Django 5.1.3 on 2025-02-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_remove_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reading',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reading',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.customer'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='previous_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='status',
        ),
    ]
