# Generated by Django 5.1.3 on 2025-03-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_company_trade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trade_name',
        ),
    ]
