# Generated by Django 5.1.3 on 2025-02-22 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_alter_reading_options_alter_reading_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='agua.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='readings',
            field=models.ManyToManyField(related_name='invoices', to='agua.reading'),
        ),
    ]
