# Generated by Django 5.1.3 on 2025-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_remove_company_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='correlative',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
