# Generated by Django 5.1.3 on 2025-03-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
