# Generated by Django 5.1.3 on 2025-03-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_reading_correlative'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='correlative',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
