# Generated by Django 5.1.3 on 2025-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_data', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('date_opening', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=13)),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
