# Generated by Django 5.1.3 on 2025-03-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_cash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePayment',
            new_name='InvoiceService',
        ),
        migrations.CreateModel(
            name='InvoiceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.invoice')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.reading')),
            ],
        ),
        migrations.DeleteModel(
            name='InvoicePayment',
        ),
    ]
