# Generated by Django 5.1.3 on 2025-02-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_remove_invoice_is_paid_alter_invoice_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='readings',
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.invoice')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.reading')),
            ],
        ),
    ]
