# Generated by Django 5.1.3 on 2025-03-25 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_rename_servicepayment_invoiceservice_invoicereading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereading',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicereading',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='agua.reading'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agua.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='agua.service'),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.cash')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agua.invoice')),
            ],
        ),
    ]
