# Generated by Django 5.1.3 on 2025-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0008_remove_invoice_readings_invoicepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepayment',
            name='amount_paid',
        ),
    ]
