# Generated by Django 5.1.3 on 2025-03-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0009_paymentmethodtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethodType',
            new_name='PaymentMethod',
        ),
    ]
