# Generated by Django 5.1.3 on 2025-03-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0010_rename_paymentmethodtype_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepayment',
            old_name='amount_paid',
            new_name='total',
        ),
    ]
