# Generated by Django 5.1.3 on 2025-02-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0010_invoicepayment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agua.reading'),
        ),
    ]
