# Generated by Django 5.1.3 on 2025-02-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0011_alter_invoicepayment_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
    ]
