# Generated by Django 5.1.3 on 2025-03-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0011_rename_amount_paid_invoicepayment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agua.paymentmethod'),
            preserve_default=False,
        ),
    ]
