# Generated by Django 5.1.3 on 2025-03-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0012_invoicepayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='cash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cash'),
        ),
    ]
