# Generated by Django 5.1.3 on 2025-04-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0013_alter_invoicepayment_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('salary', 'Sueldos'), ('maintenance', 'Mantenimiento'), ('supplies', 'Suministros'), ('services', 'Servicios'), ('other', 'Otros')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
